package login;

import at.favre.lib.crypto.bcrypt.BCrypt;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tiketkeretaapi.Koneksi;
import tiketkeretaapi.adminFrame;
import tiketkeretaapi.mainFrame;

/**
 *
 * @author RZ
 */
public class frameAuth extends javax.swing.JFrame {

	Koneksi koneksi = new Koneksi();
	Statement cmd;
	ResultSet res;
	Session sess;

	/**
	 * Creates new form frameAuth
	 *
	 * @param session
	 */
	public frameAuth(Session session) {
		sess = session;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btSubmit = new javax.swing.JButton();
        tfUsername = new javax.swing.JTextField();
        lbUsername = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Tiket Kereta Api");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        btSubmit.setBackground(new java.awt.Color(57, 62, 70));
        btSubmit.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btSubmit.setForeground(new java.awt.Color(238, 238, 238));
        btSubmit.setText("Login");
        btSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        tfUsername.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        tfUsername.setText("admin");
        tfUsername.setPreferredSize(new java.awt.Dimension(75, 50));

        lbUsername.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(0, 0, 0));
        lbUsername.setText("Username");

        lbPassword.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(0, 0, 0));
        lbPassword.setText("Password");

        tfPassword.setText("admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lbUsername)
                    .addComponent(lbPassword))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lbUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
		toggleInput(false);
		String username = tfUsername.getText().strip();
		String password = new String(tfPassword.getPassword());

		if (!username.isBlank() && !password.isBlank()) {
			if (username.equalsIgnoreCase("admin")) {
				if (password.equalsIgnoreCase("admin")) {
					setLogin("admin", null);
				} else {
					resetInput(false);
					errMessage("Password yang anda masukkan salah.");
				}
			} else {
				checkLogin(username, password);
			}
		} else {
			errMessage("Username/password tidak boleh kosong.");
		}
		toggleInput(true);
    }//GEN-LAST:event_btSubmitActionPerformed

	private void resetInput(boolean uname) {
		if (uname) {
			tfUsername.setText("");
		}
		tfPassword.setText("");
	}

	private void toggleInput(boolean status) {
		tfUsername.setEnabled(status);
		tfPassword.setEnabled(status);
		btSubmit.setEnabled(status);
	}

	private void checkLogin(String username, String password) {
		String sql = "SELECT * FROM KARYAWAN WHERE USERNAME = '" + username + "'";
		try {
			cmd = koneksi.conn.createStatement();
			res = cmd.executeQuery(sql);
			if (res.next()) {
				BCrypt.Result result = BCrypt.verifyer().verify(password.toCharArray(), res.getString("PASSWORD"));
				if (result.verified) {
					setLogin(res.getString("KODE_KARYAWAN"), res.getString("NAMA_KARYAWAN"));
				} else {
					resetInput(false);
					errMessage("Password yang anda masukkan salah.");
				}
			} else {
				resetInput(true);
				errMessage("Username belum terdaftar.");
			}
		} catch (SQLException ex) {
			Logger.getLogger(frameAuth.class.getName()).log(Level.SEVERE, null, ex);
			errMessage("Terjadi kesalahan.");
		}
	}

	private void setLogin(String kode, String nama) {

		this.dispose();
		sess.setKodeKaryawan(kode);
		if (kode.equals("admin")) {
			sess.setLevel("admin");
			adminFrame frame = new adminFrame(sess);
			frame.main(null);
		} else {
			sess.setLevel("karyawan");
			sess.setNamaKaryawan(nama);
			mainFrame frame = new mainFrame(sess);
			frame.main(null);
		}
	}

	private void errMessage(String msg) {
		JOptionPane.showMessageDialog(this, msg, "Login Gagal!", JOptionPane.ERROR_MESSAGE);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frameAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frameAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frameAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frameAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frameAuth(null).setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
